spring.application.name=fraud-detection-engine
server.port=8081

# Required connection configs for Kafka producer, consumer, and admin
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.bootstrap-servers=pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY}' password='${KAFKA_API_SECRET}';
spring.kafka.properties.security.protocol=SASL_SSL

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=dtos

# Best practice for higher availability in Apache Kafka clients prior to 3.0
spring.kafka.properties.session.timeout.ms=45000

client.id=ccloud-springboot-client-291f1ccd-2feb-4ee0-848c-4f794a796e09


#application variables

#global variable
fraud.global.block-threshold=80
fraud.global.review-threshold=20

#rules and rule variables

#blacklist rule
fraud.rules.blacklist.enabled=true
fraud.rules.blacklist.key=bip
fraud.rules.blacklist.score=100

#splurge rule
fraud.rules.splurge.enabled=true
fraud.rules.splurge.score=50
fraud.rules.splurge.key=trans-profile:

#time rule
fraud.rules.time.enabled=true
fraud.rules.time.score=50
fraud.rules.time.zone-id=UTC
fraud.rules.time.start.time=2
fraud.rules.time.end.time=6

#velocity rule
fraud.rules.velocity.enabled=true
fraud.rules.velocity.key=user-trans:
fraud.rules.velocity.score=30
fraud.rules.velocity.transaction-limit=2
fraud.rules.velocity.window.duration=60000

